apiVersion: v1
kind: Secret
metadata:
  name: faculty-db-secret
  namespace: faculty
type: Opaque
data:
  # faculty_dev_pass_7766
  db-password: ZmFjdWx0eV9kZXZfcGFzc183NzY2
  # faculty_root_dev_pass_5544
  db-root-password: ZmFjdWx0eV9yb290X2Rldl9wYXNzXzU1NDQ=
