apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-db
  namespace: exam
  labels:
    app: exam-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-db
  template:
    metadata:
      labels:
        app: exam-db
    spec:
      serviceAccountName: exam-db-sa
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:15-alpine
          args:
            - "-p"
            - "1521"
          env:
            - name: POSTGRES_USER
              value: exam_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exam-db-secret
                  key: db-password
            - name: POSTGRES_DB
              value: exam_db
          ports:
            - containerPort: 1521
              name: postgres
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
              ephemeral-storage: "50Mi"
            limits:
              memory: "128Mi"
              cpu: "250m"
              ephemeral-storage: "256Mi"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -p
                - "1521"
                - -U
                - exam_user
                - -d
                - exam_db
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -p
                - "1521"
                - -U
                - exam_user
                - -d
                - exam_db
            initialDelaySeconds: 10
            periodSeconds: 10