apiVersion: v1
kind: ServiceAccount
metadata:
  name: exam-app-sa
  namespace: exam
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exam-db-sa
  namespace: exam
automountServiceAccountToken: false
