apiVersion: v1
kind: ServiceAccount
metadata:
  name: faculty-app-sa
  namespace: faculty
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faculty-db-sa
  namespace: faculty
automountServiceAccountToken: false
