apiVersion: v1
kind: ServiceAccount
metadata:
  name: research-app-sa
  namespace: research
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: research-db-sa
  namespace: research
automountServiceAccountToken: false
