apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-app-sa
  namespace: student
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-db-sa
  namespace: student
automountServiceAccountToken: false
