apiVersion: v1
kind: Service
metadata:
  name: faculty-app
  namespace: faculty
  labels:
    app: faculty-app
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      name: http
  selector:
    app: faculty-app
