apiVersion: v1
kind: Service
metadata:
  name: student-db
  namespace: student
  labels:
    app: student-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: student-db
