apiVersion: v1
kind: Service
metadata:
  name: student-app
  namespace: student
  labels:
    app: student-app
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app: student-app
